spring:
  application:
    name: store-instituicao
  datasource:
    url: jdbc:postgresql://store-db-store:5432/store
    username: store
    password: store
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: instituicao
  jpa:
    properties:
      hibernate:
        default_schema: instituicao
  cache: 
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

management:
  endpoints:
    web:
      base-path: /instituicao/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://store-discovery:8761/eureka/

springdoc:
  api-docs:
    path: /instituicao/v3/api-docs
  swagger-ui:
    path: /instituicao/swagger-ui.html